//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enregistrement
    {
        public Enregistrement()
        {
            this.Composition_Disque = new HashSet<Composition_Disque>();
            this.Direction = new HashSet<Direction>();
            this.Interpréter = new HashSet<Interpréter>();
            this.Acheter = new HashSet<Acheter>();
        }
    
        public int Code_Enregistrement { get; set; }
        public string Titre { get; set; }
        public Nullable<int> Code_Composition { get; set; }
        public string Nom_de_Fichier { get; set; }
        public string Durée { get; set; }
        public Nullable<int> Durée_Seconde { get; set; }
        public Nullable<decimal> Prix { get; set; }
    
        public virtual Composition Composition { get; set; }
        public virtual ICollection<Composition_Disque> Composition_Disque { get; set; }
        public virtual ICollection<Direction> Direction { get; set; }
        public virtual ICollection<Interpréter> Interpréter { get; set; }
        public virtual ICollection<Acheter> Acheter { get; set; }
    }
}
